###
  ### INÍCIO DA SEÇÃO TESTE ENDPOINT EDITORAS ###
###
POST http://localhost:3000/api/editoras
Content-Type: application/json

{
  "nome": "Boa Leitura"
}

###
GET http://localhost:3000/api/editoras
Content-Type: application/json

###
GET http://localhost:3000/api/editoras/id
Content-Type: application/json

###
DELETE http://localhost:3000/api/editoras/id

###
PUT http://localhost:3000/api/editoras/id
Content-Type: application/json

{
  "nome": "Astheca Book"
}

###
  ### INÍCIO DA SEÇÃO TESTE ENDPOINT USERS ###
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "nome": "Serionando",
  "email": "serionando@tantra.com",
  "password": "123456789",
  "nivel_acesso": "admin"
}

###
GET http://localhost:3000/api/users
Content-Type: application/json

###
GET http://localhost:3000/api/users/id
Content-Type: application/json

###
DELETE http://localhost:3000/api/users/id
Content-Type: application/json

###
PUT http://localhost:3000/api/users/id
Content-Type: application/json
{
  "nome": "Fulano dos Santos",
  "email": "fulanodossantos@muzila.com",
  "password": "123456789",
  "nivel_acesso": ""
}

###
  ### INÍCIO DA SEÇÃO TESTE ENDPOINTS LIVROS ###
###
POST http://localhost:3000/api/livros
Content-Type: application/json

{
  "id_editora": "6741b54372b64bcd5ca06f15",
  "titulo": "A conquista dos que não foram",
  "resumo": "Um grupo que iria participar de um campeonato, mas na hora H desistiram. E para as suas sorte, pois o avião que iria levar o grupo sofreu um acidente, e, era para eles estarem a bordo. Assim começa essa história.",
  "autores": "Zé Ninguém, João Ninguém"
}

###
GET http://localhost:3000/api/livros
Content-Type: application/json

###
GET http://localhost:3000/api/livros/id
Content-Type: application/json

###
DELETE http://localhost:3000/api/livros/id
Content-Type: application/json

###
PUT http://localhost:3000/api/livros/id
Content-Type: application/json

{
  "id_editora": "",
  "titulo": "Um titulo do Resumo",
  "resumo": "Um resumo qualquer",
  "autores": "Fulano, Siclano, Beltrano"
}

###
  ### INÍCIO DA SEÇÃO TESTE ENDPOINTS HISTORICO ###
###
POST http://localhost:3000/api/historicos
Content-Type: application/json

{
  "id_user": "6741bb1e413aebaf97ab6381",
  "id_livro": "6741b59372b64bcd5ca06f17",
  "ultima_pagina_acessada": 0,
  "numero_paginas_lidas": 0,
  "leitura_concluida": "não",
  "visualizado": "não"
}

###
GET http://localhost:3000/api/historicos
Content-Type: application/json

###
GET http://localhost:3000/api/historicos/id
Content-Type: application/json

###
DELETE http://localhost:3000/api/historicos/id
Content-Type: application/json

###
PUT http://localhost:3000/api/historicos/id
Content-Type: application/json
{
  "id_user": "6741bb1e413aebaf97ab6381",
  "id_livro": "6741b59372b64bcd5ca06f17",
  "ultima_pagina_acessada": 16,
  "numero_paginas_lidas": 25,
  "leitura_concluida": "não",
  "visualizado": "sim"
}

